defmodule GreenAsh do
  @moduledoc """
  GreenAsh — a "green screen" test console (LiveView, 100% keyboard-driven,
  AS400 style) generated by introspection from your Ash resources, with no UI
  code.

  Mount it in your router, behind a dev-only guard — the console carries no
  access control of its own:

      if Application.compile_env(:my_app, :dev_routes) do
        import GreenAsh.Router

        scope "/" do
          pipe_through :browser
          green_ash "/cli", domains: [MyApp.Bank]
        end
      end

  See `GreenAsh.Router` for the options and for what the guard protects.
  """
end
