defmodule GreenAsh do
  @moduledoc """
  GreenAsh — a "green screen" test console (LiveView, 100% keyboard-driven,
  AS400 style) generated by introspection from your Ash resources, with no UI
  code.

  Mount it in your router:

      import GreenAsh.Router

      scope "/" do
        pipe_through :browser
        green_ash "/cli", domains: [MyApp.Bank]
      end

  See `GreenAsh.Router` for the options.
  """
end
